notifications:
  email: 
    - tobias.koppmann@gmail.com

cache:
  directories:
    - "node_modules"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"
  - sudo apt-get install python3
  - sudo apt-get install python-opencv
  
install:
  - npm install

script:
  - npm test