notifications:
  email: 
    - tobias.koppmann@gmail.com

cache:
  directories:
    - "node_modules"

matrix:
  include:
    - language: node_js
      node_js:
        - "8"

    - language: rust
      install:
        - npm install --global neon-cli
      script:
        - "neon build"