language: node_js

node_js:
  - "8"

notifications:
  email: 
    - tobias.koppmann@gmail.com

cache:
  directories:
    - "node_modules"

before_install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - source "$HOME/.cargo/env"

install:
  - npm install
  - npm run build

script:
  - npm test