[package]
name = "backend"
version = "0.1.0"
authors = ["Tobias Koppmann <tobias.koppmann@gmail.com>"]
license = "MIT"
build = "build.rs"

[lib]
name = "backend"
crate-type = ["dylib"]

[build-dependencies]
neon-build = "0.1.22"

[dependencies]
neon = "0.1.22"
